### PR TITLE
EZP-28030: Add new OE options

### PR DESCRIPTION
**Pull request by DominikaK**
https://jira.ez.no/browse/EZP-28030

(1.12)

### CODE REVIEW

**Comment by andrerom** [comment]
Seems we are missing doc on inline text formatting to be able to mention the new options for that, or?

**Comment by DominikaK** [comment]
Text formatting options are not covered intentionally, on the assumption that they are intuitive enough for anyone who has ever user any text editor.

**Comment by andrerom** [comment]
Ok, but link is covered perhaps? given it has ez specific logic in it.

**Comment by DominikaK** [comment]
Not in the user guide, following the same assumption that the UI is intuitive enough. For developer doc, AFAIR we don't have anything on links in Rich Text. Is there anything that needs adding there?

**Comment by andrerom** [comment]
Eventually for user doc imo, but not related to this change so we can move on here.

**Pull request merged**
